In [27]:
import numpy as np

In [28]:
np1 = np.array([1,2,3,'s1','s2',2+2,2*3,{'name': 'arc'}])

In [29]:
np1

array([1, 2, 3, 's1', 's2', 4, 6, {'name': 'arc'}], dtype=object)

In [30]:
type(np1)

numpy.ndarray

In [31]:
np2 = np.array(list(range(1,50,2)))

In [32]:
np2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [33]:
print(np.min(np2))

1


In [34]:
l1 = list(range(10,100,5))

In [35]:
l1

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [36]:
print(np.min(l1))

10


In [37]:
np3 = np.array([[0,1,2],[2,4,5]])

In [38]:
print(np3)

[[0 1 2]
 [2 4 5]]


In [39]:
print(l1)
print()
print(np1)
print()
print(np2)
print()
print(np3)

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

[1 2 3 's1' 's2' 4 6 {'name': 'arc'}]

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]

[[0 1 2]
 [2 4 5]]


In [40]:
print(f'np1.shape() = {np1.shape}')
print()
print(f'np2.shape() = {np2.shape}')
print()
print(f'np3.shape() = {np3.shape}')
print()
print(f'l1.shape() = {len(l1)}')

np1.shape() = (8,)

np2.shape() = (25,)

np3.shape() = (2, 3)

l1.shape() = 18


In [41]:
print(f'type(np1) = {type(np1)}   ,  np1.dtype = {np1.dtype}')

type(np1) = <class 'numpy.ndarray'>   ,  np1.dtype = object


In [42]:
print(f'type(np2) = {type(np2)}   ,  np2.dtype = {np2.dtype}')

print(f'type(np3) = {type(np3)}   ,  np3.dtype = {np3.dtype}')



type(np2) = <class 'numpy.ndarray'>   ,  np2.dtype = int32
type(np3) = <class 'numpy.ndarray'>   ,  np3.dtype = int32


In [43]:
np3

array([[0, 1, 2],
       [2, 4, 5]])

In [44]:
l2 = [[0, 1, 2],
       [2, 4, 5]]

l2

[[0, 1, 2], [2, 4, 5]]

In [45]:
l2[0][1] = 3

l2

[[0, 3, 2], [2, 4, 5]]

In [46]:
np3[0,1] = 3

np3

array([[0, 3, 2],
       [2, 4, 5]])

In [47]:
l2[0][1] = 'text'

l2

[[0, 'text', 2], [2, 4, 5]]

In [48]:
np3[0,1] = 'text'

np3

ValueError: invalid literal for int() with base 10: 'text'

In [ ]:
mat2 = np.arange(10,100,5)

mat2

print(f'mat2 {mat2}')

nprange = np.array(range(10,100,5))

print(f'nprange = {nprange}')



mat2 [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
nprange = [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
mat3 = np.linspace(0,10,20)

print(mat3)

print(mat3.shape)
len(mat3)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
(20,)


20

In [ ]:
mat4 = np.random.rand(5,5)

print(mat4)

[[0.94890758 0.21629187 0.94988441 0.99994097 0.35207229]
 [0.25647738 0.16943666 0.55445108 0.50401944 0.4836531 ]
 [0.65487196 0.0471302  0.31765134 0.6765057  0.11959113]
 [0.29352795 0.05113195 0.12300771 0.24140823 0.30527342]
 [0.38668601 0.56794657 0.96813423 0.23378936 0.73780848]]


# Numpy

### np.array

In [59]:
d1 = np.array([1,2,3,4,5])

d1

array([1, 2, 3, 4, 5])

### np.zeros

In [51]:
d2 = np.zeros((4, 4))

d2

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### np.ones

In [54]:
d3 = np.ones((4, 4))

d3

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### np.random.uniform

In [55]:
d4 = np.random.uniform(5,10,size = 4)

d4

[7.18733848 7.58534763 8.07813021 6.03345349]


### np.random.randint

In [58]:
d5 = np.random.randint(5,10,10)

d5

[8 7 6 7 6 8 8 6 7 6]


array([8, 7, 6, 7, 6, 8, 8, 6, 7, 6])

### np.random.random

In [61]:
d6 = np.random.random(3)

d6

array([0.52098564, 0.89602603, 0.09317008])

### np.full














In [65]:
d7 = np.full((2,4),fill_value=2)

d7

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

### np.identity

In [67]:
d8 = np.identity(4)

d8

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.min

In [70]:
d9 = np.array([1,1,2,3,3,4,5,6,6,2])
d9_min = np.min(d9)

print(d9)
d9_min

[1 1 2 3 3 4 5 6 6 2]


1

### np.max

In [71]:
d9_max = np.max(d9)

d9_max

6

##  basic operations

### add

In [72]:
a = np.array([10,20,30])
b= np.array([1,2,3])
print("addition of a and b :",np.add(a,b))


addition of a and b : [11 22 33]


### multiply

In [73]:
print("multiplication of a and b :",np.multiply(a,b))


multiplication of a and b : [10 40 90]


### subtract

In [74]:
print("subtraction of a and b :",np.subtract(a,b))


subtraction of a and b : [ 9 18 27]


### power

In [75]:
print("a raised to b is:",np.power(a,b))

a raised to b is: [   10   400 27000]


### division

In [76]:
a = np.array([10,20,30])
b= np.array([2,3,4])
print("division of a and b :",np.divide(a,b))


division of a and b : [5.         6.66666667 7.5       ]


### mod

In [77]:

print("mod of a and b :",np.mod(a,b))


mod of a and b : [0 2 2]


### divmod

In [78]:
print("quotient and remainder of a and b :",np.divmod(a,b))


quotient and remainder of a and b : (array([5, 6, 7]), array([0, 2, 2]))


### remainder

In [79]:
print("remainders when a/b :",np.remainder(a,b))

remainders when a/b : [0 2 2]


### square root

In [80]:
arSq = np.array([2,4,6])

print("Square Root Result:", np.sqrt(arSq))

Square Root Result: [1.41421356 2.         2.44948974]


### shape

In [82]:
ab = np.array([[1, 2, 3], [4, 5, 6]])
shape = ab.shape
print("Array Shape:", shape)

Array Shape: (2, 3)


### size

In [83]:
size = ab.size
print("Array Size:", size)

Array Size: 6


### dtype

In [84]:
dtype = ab.dtype
print("Data Type:", dtype)

Data Type: int32


### sum

In [89]:
d10 = np.array([4, 2, 9, 5, 1, 8, 6, 3, 7])

print("Sum:", np.sum(d10))

Sum: 45


### mean

In [90]:

print("Mean:",np.mean(d10))

Mean: 5.0


### median

In [91]:

print("Median:", np.median(d10))

Median: 5.0


### std

In [92]:

print("Standard Deviation:", np.std(d10))

Standard Deviation: 2.581988897471611


### reshape

In [96]:

d11 = np.arange(12)
print(d11)
print("Reshaped array (3x4)",d11.reshape((3, 4)))


[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x4) [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Transpose

In [98]:
d12 = np.array([[1, 2, 3], [4, 5, 6]])

print("Transposed array", d12.transpose())

Transposed array [[1 4]
 [2 5]
 [3 6]]


### Save


In [100]:
d13 = np.array([1, 2, 3, 4, 5])
print(np.save('my_array.npy', d13))

None


### Load

In [104]:

loaded_arr = np.load('my_array.npy')
print("Loaded array", loaded_arr)


Loaded array [1 2 3 4 5]



### NaN and isnan


In [105]:
d13 = np.array([1, 2, np.nan, 4, np.nan, 6])
nan_mask = np.isnan(d13)
print("Array with NaNs:\n", d13)
print("NaN mask:\n", nan_mask)
num_nans = np.sum(nan_mask)
print("Number of NaNs:", num_nans)

Array with NaNs:
 [ 1.  2. nan  4. nan  6.]
NaN mask:
 [False False  True False  True False]
Number of NaNs: 2


### where

In [109]:

d14 = np.array([1, 2, 3, 4, 5, 6])
condition = d14 > 3
result = np.where(condition)
print("Indices of elements > 3:\n", result)
replaced_arr = np.where(arr > 3, arr * 10, arr)

print("Array with elements > 3 multiplied by 10:\n", replaced_arr)

Indices of elements > 3:
 (array([3, 4, 5], dtype=int64),)
Array with elements > 3 multiplied by 10:
 [ 1  2  3 40 50]
